# fly.toml file generated for delicate-pond-4354 on 2022-07-08T10:02:32+02:00

app = "delicate-pond-4354"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[[services]]
  internal_port = 7337
  http_checks = []
  tcp_checks = []
  protocol = "tcp"